#baseurl: "http://engineering.facile.it/"
baseurl: "/"
languageCode: "en-us"
title: "Facile.it Engineering"
paginate: 5
theme: "hugo-future-imperfect"
#DisqusShortname: "facile-it"
Copyright: "All rights reserved - 2016"
canonifyurls: true

params:
  sidebartitle: "Facile.it Engineering"
#  sidebarphoto: "/img/photo.png"
  sidebartagline: "News, repos, tips & trends from the Facile.it Engineering team!"
  cover: "images/cover.jpg"
  logo: "images/logo.png"
  author: "Facile.it Engineering"
  authorlocation: "Milano, Italy"
#  bio: "my bio"
#  googleAnalyticsUserID: "UA-22342495-1"
  authorwebsite: "http://www.facile.it"
  facebookName: "facile.it"
  githubName: "facile-it"
  twitterName: "FacileIt_Engr"
  linkedinName: "facile-it"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport: false
